---
- name: install server
  hosts: webservers

  tasks:
   - name: install apache 
     ansible.builtin.apt:
             name: apache2
             state: latest
   - name: ensure apache is running
     ansible.builtin.service:
         name: apache2
         state: started
